{
 "title": "PiCluster",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Raspberry Pi Temperatures",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rpi_cpu_temperature_celsius" }
   ]
  },
  {
   "title": "main network status",
   "type": "vonage-status-panel",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "eth0",
     "crit": 100,
     "disabledValue": "0",
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "node_network_up{device=\"wlan0\", job=\"main\"} OR on() vector(100)",
     "legendFormat": "eth0",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 50
    }
   ]
  },
  {
   "title": "miniom1 network status",
   "type": "vonage-status-panel",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 10 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "eth0",
     "crit": 100,
     "disabledValue": "0",
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "node_network_up{device=\"wlan0\", job=\"minion1\"} OR on() vector(100)",
     "legendFormat": "eth0",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 50
    }
   ]
  },
  {
   "title": "main RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(((node_memory_MemTotal_bytes{job=\"main\"} - node_memory_MemFree_bytes{job=\"main\"} - node_memory_Buffers_bytes{job=\"main\"} - node_memory_Cached_bytes{job=\"main\"}) / node_memory_MemTotal_bytes{job=\"main\"}) * 100)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "minion1 RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(((node_memory_MemTotal_bytes{job=\"minion1\"} - node_memory_MemFree_bytes{job=\"minion1\"} - node_memory_Buffers_bytes{job=\"minion1\"} - node_memory_Cached_bytes{job=\"minion1\"}) / node_memory_MemTotal_bytes{job=\"minion1\"}) * 100)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "main CPU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"main\", mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "minion1 CPU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"minion1\", mode=\"idle\"}[5m])) * 100)"
    }
   ]
  }
 ]
}